type: robot_local_control_components/NavigationComponent
desired_freq: 1.0

check_sensors_state: false
check_localization_state: false
has_safety_laser: false
safety_laser_mode_allowed: safe

#components: [GoToComponent, ChargeComponent, UnchargeComponent, MoveComponent]
components:
 - GoToComponent
 - MoveComponent
 - ChargeComponent
 - UnchargeComponent

GoToComponent:
  type: robot_local_control_procedures/GoToMoveBase
  desired_freq: 5.0
  action_namespace: move_base
  global_frame: robot_map
  base_frame: robot_base_footprint
  default_yaw_tolerance: 0.1 # when goal has orientation. if orientation is invalid, goal tolerance is changed to 3.14
  has_safety_laser: false
  yaw_tolerance: 0.1
  xy_tolerance: 0.15
  preemptable: false
  clear_costmaps_before_send_goal: false
  local_planner_namespace: TebLocalPlannerROS

MoveComponent:
  type: robot_local_control_procedures/Move
  desired_freq: 5.0
  action_namespace: move

ChargeComponent:
  type: robot_local_control_procedures/Charge
  desired_freq: 5.0
  has_laser_safety: false # determines if the robot has safety_lasers and the safety zone must be changed
  docker_namespace: pp_docker
  dock_frame: robot_docking_station_laser_filtered
  robot_dock_frame: robot_base_footprint
  dock_offset_x: -0.65 
  move_namespace: move
  step_in_distance: 0.05 # Indicates the distance that the robot is going to move in x-axis after the docking. If 0.0 then no move action is done
  set_to_standby: false # If 'true' then the lasers will be in standby after the docking

UnchargeComponent:
  type: robot_local_control_procedures/Uncharge
  desired_freq: 5.0
  has_laser_safety: false # determines if the robot has safety_lasers and the safety zone must be changed
  move_namespace: move
  step_back_distance: 0.3 # Indicates the distance that the robot is going to move backwards. If 0.0 then no rotation action is done
  rotation: 3.14 # Indicates the rotation that the robot is going to move after moving backwards. If 0.0 then no rotation action is done
