global_frame: map
robot_base_frame: rbkairos_a/base_footprint
static_map: false
update_frequency: 2.0
publish_frequency: 2.0

plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
