global_costmap:
  global_frame: map
  robot_base_frame: $(arg base_frame)
  update_frequency: 10.0
  publish_frequency: 10.0
  
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: robot_detection_layer,   type: "robot_detection_layer::RobotDetectionLayer"}
    - {name: human_detection_layer,   type: "human_detection_layer::HumanDetectionLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
    