global_frame: map
#  global_frame: /odom_combined
robot_base_frame: rbkairos_a/base_footprint
publish_frequency: 2.0
update_frequency: 2.0
static_map: false
rolling_window: true
width: 5.0 
height: 5.0 
resolution: 0.05

#  obstacle_laser_layer:
#    observation_sources: front_laser
#    front_laser: 
#      data_type: LaserScan
#      topic: front_laser/scan
#      marking: true
#      clearing: true
#      observation_persistence: 0.0
#    inf_is_valid: true
#    track_unknown_space: true
#    footprint_clearing_enabled: true
